[build.environment]
  NODE_VERSION = "14"

[[redirects]]
  from = "/api/event"
  to = "https://plausible.io/api/event"
  status = 200

[[redirects]]
  from = "/"
  to = "/protocols/"

[[redirects]]
  from = "/protocols/*"
  to = "/protocols/404.html"
  status = 404
